### ISSUE TITLE
npm install throws errors

### ISSUE THREAD

**Issue by gurupras** [DCzajkowski/vue-emoji-picker#20] opened 2020-11-01 17:07 UTC
This may have something to do with my setup, but I'm not too knowledgeable when it comes to npm versions/scripts. Posting this here hoping someone can fix it :confused: 

```sh
guru@dileant:~/workspace/nodejs-libraries/vue-emoji-picker$ npm install
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> vue-emoji-picker@1.0.2 prepublish /home/guru/workspace/nodejs-libraries/vue-emoji-picker
> npm run build && npm run browser-build


> vue-emoji-picker@1.0.2 build /home/guru/workspace/nodejs-libraries/vue-emoji-picker
> cross-env NODE_ENV=production webpack --progress --hide-modules

Hash: f725c707b1e578a2814b                                                         
Version: webpack 2.7.0
Time: 637ms
      Asset     Size  Chunks             Chunk Names
    main.js  14.6 kB       0  [emitted]  main
main.js.map  65.7 kB       0  [emitted]  main

> vue-emoji-picker@1.0.2 browser-build /home/guru/workspace/nodejs-libraries/vue-emoji-picker
> cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o dist/vue-emoji-picker.css ] -e src/main.js | uglifyjs -c warnings=false -m > dist/vue-emoji-picker.js

sh: 1: cannot create dist/vue-emoji-picker.js: Directory nonexistent
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! vue-emoji-picker@1.0.2 browser-build: `cross-env NODE_ENV=production browserify -g envify -p [ vueify/plugins/extract-css -o dist/vue-emoji-picker.css ] -e src/main.js | uglifyjs -c warnings=false -m > dist/vue-emoji-picker.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the vue-emoji-picker@1.0.2 browser-build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! vue-emoji-picker@1.0.2 prepublish: `npm run build && npm run browser-build`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the vue-emoji-picker@1.0.2 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by DCzajkowski** [comment] 2020-11-01 23:55
I think the issue is, you need to create an empty `dist/` directory manually. 🙂

**Comment by DCzajkowski** [comment] 2021-06-16 20:14
I am closing this. If the problem persists let me know.

**Closed by DCzajkowski** 2021-06-16 20:14 UTC
