### ISSUE TITLE
insert an emoji in the middle of the text

### ISSUE THREAD

**Issue by xcesaralejandro** [DCzajkowski/vue-emoji-picker#14] opened 2019-11-03 00:40 UTC
Do you have any option to insert emojis in the middle of the text?

For example:
  If I write "Hello World!" and then I click between Hello and World to insert an emoji there, it is added by default at the end.

https://codepen.io/DCzajkowski/pen/JLypqP

**Comment by DCzajkowski** [comment] 2019-11-03 20:59
Duplicate of #11 :)

**Closed by DCzajkowski** 2019-11-03 20:59 UTC
